#
# -*- coding: utf-8 -*-
# Copyright 2025 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the saos10_ldp module
"""
from __future__ import absolute_import, division, print_function


__metaclass__ = type


class LdpArgs(object):  # pylint: disable=R0903
    """The arg spec for the saos10_ldp module"""

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "tag": {"type": "str", "required": True},
                "control_mode": {"type": "str", "choices": ["independent", "ordered"]},
                "graceful_restart": {
                    "type": "dict",
                    "options": {
                        "enable": {"type": "bool"},
                        "helper_enable": {"type": "bool"},
                        "timers": {
                            "type": "dict",
                            "options": {"max_recovery": {"type": "int"}, "neighbor_liveness": {"type": "int"}},
                        },
                    },
                },
                "hello_holdtime": {"type": "int"},
                "hello_interval": {"type": "int"},
                "inter_area_lsp": {"type": "bool"},
                "interfaces": {
                    "type": "dict",
                    "options": {
                        "interface": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "name": {"type": "str", "required": True},
                                "enable_ipv4": {"type": "bool"},
                                "hello_holdtime": {"type": "int"},
                                "hello_interval": {"type": "int"},
                                "keepalive_interval": {"type": "int"},
                                "keepalive_timeout": {"type": "int"},
                                "ldp_igp_sync_delay_interval": {"type": "int"},
                            },
                        }
                    },
                },
                "keepalive_interval": {"type": "int"},
                "keepalive_timeout": {"type": "int"},
                "lsr_id": {"type": "str"},
                "peers": {
                    "type": "dict",
                    "options": {
                        "peer": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "lsr_id": {"type": "str", "required": True},
                                "password": {"type": "str", "no_log": True},
                            },
                        }
                    },
                },
                "pw_status_tlv": {"type": "bool"},
                "target_ldp": {
                    "type": "dict",
                    "options": {
                        "peers": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "address": {"type": "str", "required": True},
                                "hello_holdtime": {"type": "int"},
                                "hello_interval": {"type": "int"},
                            },
                        }
                    },
                },
                "targeted_hello_holdtime": {"type": "int"},
                "targeted_hello_interval": {"type": "int"},
                "transport": {"type": "dict", "options": {"address": {"type": "str"}}},
            },
        },
        "state": {"type": "str", "default": "merged", "choices": ["merged", "deleted"]},
    }  # pylint: disable=C0301
