---
namespace: ciena
name: saos10
version: 1.7.0
authors:
  - Jeff Groom (github.com/jgroom33)
description: Ansible collection for Ciena's SAOS 10
dependencies:
  ansible.netcommon: ">=2.5.1"
license_file: LICENSE
readme: README.md
repository: https://github.com/ciena/ciena.saos10
homepage: https://github.com/ciena/ciena.saos10
issues: https://github.com/ciena/ciena.saos10/issues
tags: [ciena, saos, networking, ethernet, netconf]
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - .vscode
  - .github
