#
# -*- coding: utf-8 -*-
# Copyright 2021 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the saos10_classifiers module
"""
from __future__ import absolute_import, division, print_function


__metaclass__ = type


class ClassifiersArgs(object):  # pylint: disable=R0903
    """The arg spec for the saos10_classifiers module"""

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "name": {"type": "str"},
                "filter_operation": {"type": "str", "choices": ["match-all", "match-any"]},
                "filter_entry": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "filter_parameter": {
                            "type": "str",
                            "choices": [
                                "vtag-stack",
                                "mpls-label-stack",
                                "dscp",
                                "source-ip",
                                "destination-ip",
                                "l4-source-port",
                                "l4-destination-port",
                                "ip-protocol",
                                "base-etype",
                                "any",
                                "ip-fragment",
                                "l4-application",
                                "tcp-flags",
                                "source-mac",
                                "destination-mac",
                                "local-termination",
                                "icmp",
                                "ip-version",
                                "internal-cos",
                            ],
                        },
                        "logical_not": {"type": "bool"},
                        "untagged-exclude-priority-tagged": {"type": "bool"},
                        "vtags": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "tag": {"type": "int", "required": True},
                                "vlan-id": {"type": "int", "required": True},
                            },
                        },
                    },
                },
            },
        },
        "state": {"type": "str", "default": "merged", "choices": ["merged", "overridden", "deleted"]},
    }  # pylint: disable=C0301
