#
# -*- coding: utf-8 -*-
# Copyright 2025 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the saos10_ptps module
"""
from __future__ import absolute_import, division, print_function


__metaclass__ = type


class PtpsArgs(object):  # pylint: disable=R0903
    """The arg spec for the saos10_ptps module"""

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "ptp_id": {"type": "str", "required": True},
                "properties": {
                    "type": "dict",
                    "options": {
                        "forward_error_correction": {"type": "str", "choices": ["disabled", "enabled"]},
                        "parent_id": {"type": "str"},
                        "thresholds": {
                            "type": "dict",
                            "options": {"pre_fec_sd_dbq": {"type": "float"}, "pre_fec_sf_dbq": {"type": "float"}},
                        },
                        "transmitter": {
                            "type": "dict",
                            "options": {"state": {"type": "str", "choices": ["disabled", "enabled", "not-applicable"]}},
                        },
                        "xcvr_type": {
                            "type": "str",
                            "choices": [
                                "not-available",
                                "unsupported",
                                "QSFPplus",
                                "QSFP28",
                                "WaveLogic 3 Extreme",
                                "WaveLogic Ai",
                                "Sgmii",
                                "CFP",
                                "SFP",
                                "SFPplus",
                                "XFP",
                                "SFPplus tdwdm",
                                "CFP2",
                                "CFP2-DCO",
                                "CFP2-ACO",
                                "CEP001-OC3",
                                "CEP002-OC3-OC12",
                                "CEP003-DS3-E3",
                                "GES101-OC3-STM1",
                                "TDM2GE-E1",
                                "TDM4GE-DS1",
                                "TSOP01-OC3-STM1",
                                "TSOP02-OC12-STM4",
                                "TSOP03-OC48-STM16",
                                "NATIVE-OC3-OC12",
                                "NATIVE-OC48",
                                "QSFP56",
                                "QSFPDD",
                                "SFP28",
                                "Fixed-Copper",
                                "SFPDD",
                                "QSFPDD-AOC",
                                "QSFPDD-DAC",
                                "QSFPDD-WaveLogic-5n",
                                "SFP56",
                            ],
                        },
                    },
                },
                "state": {
                    "type": "dict",
                    "options": {
                        "admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                        "spli_management": {"type": "str", "choices": ["disabled", "enabled"]},
                    },
                },
            },
        },
        "state": {"type": "str", "default": "merged", "choices": ["merged", "deleted"]},
    }  # pylint: disable=C0301
