#
# -*- coding: utf-8 -*-
# Copyright 2021 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the saos10_fds module
"""
from __future__ import absolute_import, division, print_function


__metaclass__ = type


class FdsArgs(object):  # pylint: disable=R0903
    """The arg spec for the saos10_fds module"""

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "description": {"type": "str"},
                "name": {"type": "str"},
                "mode": {
                    "type": "str",
                    "choices": ["vlan", "vpls", "vpws", "fxc", "tdm-vpls", "tdm-vpws", "evpn-vpws", "evpn-vpls"],
                },
                "vlan_id": {"type": "int"},
                "mac_learning": {"type": "str", "choices": ["enabled", "disabled"]},
                "l2cp_profile": {"type": "str"},
                "flood_containment_profile": {"type": "str"},
                "pfg_profile": {"type": "str"},
                "cos_queue_map": {"type": "str"},
                "queue_group_indirection": {"type": "str"},
                "initiate_l2_transform": {
                    "type": "dict",
                    "options": {"frame_type": {"type": "str", "choices": ["stack"]}},
                },
                "initiate_cos_to_frame_map": {"type": "str"},
                "initiate_frame_to_cos": {"type": "str", "choices": ["map", "fixed"]},
            },
        },
        "state": {"type": "str", "default": "merged", "choices": ["merged", "overridden", "deleted"]},
    }  # pylint: disable=C0301
