#
# -*- coding: utf-8 -*-
# Copyright 2021 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the saos10_fds module
"""


class FdsArgs(object):  # pylint: disable=R0903
    """The arg spec for the saos10_fds module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "elements": "dict",
            "options": {
                "initiate-l2-transform": {
                    "options": {
                        "vlan-stack": {
                            "elements": "dict",
                            "options": {
                                "push-dei": {
                                    "choices": ["enabled", "disabled"],
                                    "type": "str",
                                },
                                "push-pcp": {
                                    "choices": [
                                        "pcp-0",
                                        "pcp-1",
                                        "pcp-2",
                                        "pcp-3",
                                        "pcp-4",
                                        "pcp-5",
                                        "pcp-6",
                                        "pcp-7",
                                        "map",
                                    ],
                                    "type": "str",
                                },
                                "push-tpid": {
                                    "choices": ["tpid-8100", "tpid-88a8", "tpid-9100"],
                                    "default": "tpid-8100",
                                    "type": "str",
                                },
                                "push-vid": {"required": True, "type": "str"},
                                "tag": {"type": "int"},
                            },
                            "type": "list",
                        }
                    },
                    "type": "dict",
                },
                "mode": {
                    "choices": [
                        "vpls",
                        "vpws",
                        "fxc",
                        "tdm-vpls",
                        "tdm-vpws",
                        "evpn-vpws",
                        "evpn-vpls",
                    ],
                    "type": "str",
                },
                "name": {"required": True, "type": "str"},
                "pfg-profile": {"type": "str"},
                "vlan-id": {"type": "int"},
            },
            "type": "list",
        },
        "state": {
            "choices": ["merged", "overridden", "deleted"],
            "default": "merged",
            "type": "str",
        },
    }  # pylint: disable=C0301
