#
# -*- coding: utf-8 -*-
# Copyright 2021 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the saos10_fds module
"""
from __future__ import absolute_import, division, print_function


__metaclass__ = type


class FdsArgs(object):  # pylint: disable=R0903
    """The arg spec for the saos10_fds module"""

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "description": {"type": "str"},
                "name": {"type": "str"},
                "mode": {
                    "type": "str",
                    "choices": ["vlan", "vpls", "vpws", "fxc", "tdm-vpls", "tdm-vpws", "evpn-vpws", "evpn-vpls"],
                },
                "vlan_id": {"type": "int"},
                "mac_learning": {"type": "str", "choices": ["enabled", "disabled"]},
                "l2cp_profile": {"type": "str"},
                "flood_containment_profile": {"type": "str"},
                "pfg_profile": {"type": "str"},
                "cos_queue_map": {"type": "str"},
                "queue_group_indirection": {"type": "str"},
                "initiate_l2_transform": {
                    "type": "dict",
                    "options": {
                        "vlan_stack": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "tag": {"type": "int"},
                                "push_tpid": {"type": "str", "choices": ["tpid-8100", "tpid-88a8", "tpid-9100"]},
                                "push_pcp": {
                                    "type": "str",
                                    "choices": [
                                        "pcp-0",
                                        "pcp-1",
                                        "pcp-2",
                                        "pcp-3",
                                        "pcp-4",
                                        "pcp-5",
                                        "pcp-6",
                                        "pcp-7",
                                        "map",
                                    ],
                                },
                                "push_dei": {"type": "str", "choices": ["enabled", "disabled"]},
                                "push_vid": {"type": "int", "required": True},
                            },
                        }
                    },
                },
                "initiate_cos_to_frame_map": {"type": "str"},
                "initiate_frame_to_cos_map_policy": {
                    "type": "str",
                    "choices": ["outer-tag", "inner-tag", "mpls-tc", "dscp"],
                },
                "initiate_frame_to_cos_map": {"type": "str"},
                "cos": {"type": "int"},
                "color": {"type": "str", "choices": ["green", "yellow", "red"]},
            },
        },
        "state": {"type": "str", "default": "merged", "choices": ["merged", "overridden", "deleted"]},
    }  # pylint: disable=C0301
