#
# -*- coding: utf-8 -*-
# Copyright 2021 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the saos10_fps module
"""
from __future__ import absolute_import, division, print_function


__metaclass__ = type


class FpsArgs(object):  # pylint: disable=R0903
    """The arg spec for the saos10_fps module"""

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "description": {"type": "str"},
                "type": {"type": "str", "choices": ["q-in-q", "mpls-pw", "uni", "other"]},
                "name": {"type": "str"},
                "fd_name": {"type": "str"},
                "logical_port": {"type": "str"},
                "mtu_size": {"type": "int"},
                "admin_state": {"type": "str", "choices": ["enabled", "disabled"]},
                "ingress_l2_transform": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "ingress_name": {"type": "str"},
                        "frame_type": {"type": "str", "choices": ["stack", "untagged"]},
                    },
                },
                "egress_l2_transform": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "egress_name": {"type": "str"},
                        "frame_type": {"type": "str", "choices": ["stack", "untagged"]},
                    },
                },
                "ingress_l3_transform": {"type": "str", "choices": ["map", "remark-dscp"]},
                "egress_l3_transform": {"type": "str", "choices": ["map", "remark-dscp"]},
                "frame_to_cos": {"type": "str", "choices": ["map", "fixed"]},
                "cos_to_frame_map": {"type": "str"},
                "flood_containment_profile": {"type": "str"},
                "classifier_list": {"type": "str"},
                "classifier_list_precedence": {"type": "int"},
                "mac_learning": {"type": "str", "choices": ["enabled", "disabled"]},
                "meter_profile": {"type": "str"},
                "pfg_group": {
                    "type": "str",
                    "choices": ["leaf", "root", "dynamic", "mesh", "spoke", "group-A", "group-B", "group-C", "group-D"],
                },
                "queue_group_instance": {"type": "str"},
                "stats_collection": {"type": "str", "choices": ["on", "off"]},
                "normalized_vid": {
                    "type": "list",
                    "elements": "dict",
                    "options": {"tag": {"type": "int"}, "vlan_id": {"type": "int"}},
                },
            },
        },
        "state": {"type": "str", "default": "merged", "choices": ["merged", "overridden", "deleted"]},
    }  # pylint: disable=C0301
