#
# -*- coding: utf-8 -*-
# Copyright 2025 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the saos10_bgp module
"""
from __future__ import absolute_import, division, print_function


__metaclass__ = type


class BgpArgs(object):  # pylint: disable=R0903
    """The arg spec for the saos10_bgp module"""

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "as": {"type": "int", "required": True},
                "address_family": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "afi": {
                            "type": "str",
                            "choices": ["ipv4", "ipv6", "vpnv4", "vpnv6", "rtfilter", "l2vpn", "link-state", "all"],
                            "required": True,
                        },
                        "safi": {
                            "type": "str",
                            "choices": [
                                "unicast",
                                "multicast",
                                "labeled-unicast",
                                "l2vpn-vpls",
                                "evpn",
                                "vpn-unicast",
                                "rtfilter-unicast",
                                "link-state",
                                "all",
                            ],
                            "required": True,
                        },
                        "additional_paths": {
                            "type": "dict",
                            "options": {
                                "type": {"type": "list", "elements": "str", "choices": ["receive", "send"]},
                                "best_count": {"type": "int"},
                                "install": {"type": "bool"},
                                "select_all": {"type": "bool"},
                            },
                        },
                        "aggregate_address": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "address": {"type": "str", "required": True},
                                "as_set": {"type": "bool"},
                                "summary_only": {"type": "bool"},
                            },
                        },
                        "allocate_label": {
                            "type": "dict",
                            "options": {
                                "all": {"type": "bool"},
                                "implicit_null": {"type": "bool"},
                                "policy": {"type": "str"},
                            },
                        },
                        "auto_summary": {"type": "bool"},
                        "network": {
                            "type": "list",
                            "elements": "dict",
                            "options": {"address": {"type": "str", "required": True}, "policy": {"type": "str"}},
                        },
                        "network_synchronization": {"type": "bool"},
                        "pic": {"type": "bool"},
                        "redistribute": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "protocol": {
                                    "type": "str",
                                    "choices": ["kernel", "connected", "static", "rip", "isis", "ospf"],
                                    "required": True,
                                },
                                "instance": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {"tag": {"type": "str", "required": True}, "policy": {"type": "str"}},
                                },
                                "policy": {"type": "str"},
                            },
                        },
                        "route_reflector": {"type": "bool"},
                        "segment_routing": {"type": "str", "choices": ["enable", "disable"]},
                        "segment_routing_srv6": {"type": "dict", "options": {"locator": {"type": "str"}}},
                        "synchronization": {"type": "bool"},
                        "table_map": {
                            "type": "dict",
                            "options": {"filter": {"type": "bool"}, "policy": {"type": "str"}},
                        },
                    },
                },
                "aigp_threshold": {"type": "int"},
                "cluster_id": {"type": "str"},
                "extended_asn_cap": {"type": "bool"},
                "fast_external_failover": {"type": "bool"},
                "graceful_restart": {
                    "type": "dict",
                    "options": {
                        "deferral_time": {"type": "int"},
                        "enable": {"type": "bool"},
                        "restart_time": {"type": "int"},
                        "stalepath_time": {"type": "int"},
                    },
                },
                "hold_time": {"type": "int"},
                "inbound_route_filter": {"type": "bool"},
                "keepalive_interval": {"type": "int"},
                "l2vpn_vpls": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "route_distinguisher": {"type": "str"},
                        "route_target": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "direction": {"type": "str", "choices": ["import", "export", "both"], "required": True},
                                "id": {"type": "str", "required": True},
                            },
                        },
                        "vpls_id": {"type": "str"},
                    },
                },
                "local_preference": {"type": "int"},
                "log_peer_changes": {"type": "bool"},
                "mpls_resolution": {"type": "bool"},
                "next_hop_tracking": {
                    "type": "dict",
                    "options": {"delay": {"type": "int"}, "enable": {"type": "bool"}},
                },
                "peer": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "address": {"type": "str", "required": True},
                        "description": {"type": "str"},
                        "address_family": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "afi": {"type": "str", "required": True},
                                "safi": {"type": "str", "required": True},
                                "activate": {"type": "bool"},
                                "additional_paths": {
                                    "type": "dict",
                                    "options": {
                                        "type": {
                                            "type": "str",
                                            "choices": ["receive", "send", "send-receive", "disable"],
                                        },
                                        "best_count": {"type": "int"},
                                        "select_all": {"type": "bool"},
                                    },
                                },
                                "advertise_ip_prefix": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "afi": {"type": "str", "choices": ["vpnv4", "vpnv6"], "required": True}
                                    },
                                },
                                "aigp": {
                                    "type": "dict",
                                    "options": {
                                        "enable": {"type": "bool"},
                                        "send": {
                                            "type": "dict",
                                            "options": {
                                                "community": {
                                                    "type": "dict",
                                                    "options": {
                                                        "cost": {"type": "int"},
                                                        "point_of_insertion": {
                                                            "type": "str",
                                                            "choices": ["pre-bestpath", "igp-cost"],
                                                        },
                                                        "transitive": {"type": "bool"},
                                                    },
                                                },
                                                "med": {"type": "bool"},
                                            },
                                        },
                                    },
                                },
                                "allow_as_in": {"type": "int"},
                                "allow_ebgp_sr": {"type": "str", "choices": ["enable", "disable"]},
                                "allow_ebgp_vpn": {"type": "bool"},
                                "attribute_unchanged": {
                                    "type": "list",
                                    "elements": "str",
                                    "choices": ["as-path", "next-hop", "med"],
                                },
                                "default_originate": {"type": "bool"},
                                "default_originate_vpn": {
                                    "type": "dict",
                                    "options": {
                                        "vrf": {
                                            "type": "list",
                                            "elements": "dict",
                                            "options": {"name": {"type": "str", "required": True}},
                                        }
                                    },
                                },
                                "graceful_restart_helper": {"type": "str", "choices": ["disable", "enable"]},
                                "next_hop_self": {"type": "bool"},
                                "orf_mode": {"type": "str", "choices": ["both", "receive", "send"]},
                                "policy": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "direction": {"type": "str", "choices": ["in", "out"], "required": True},
                                        "name": {"type": "str", "required": True},
                                    },
                                },
                                "prefix_limit": {
                                    "type": "dict",
                                    "options": {
                                        "drop_excess": {"type": "float"},
                                        "idle_timeout": {"type": "int"},
                                        "maximum_prefixes": {"type": "int"},
                                        "teardown_threshold": {"type": "float"},
                                        "warning_only": {"type": "bool"},
                                    },
                                },
                                "prefix_list": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "direction": {
                                            "type": "list",
                                            "elements": "str",
                                            "choices": ["in", "out"],
                                            "required": True,
                                        },
                                        "name": {"type": "str", "required": True},
                                    },
                                },
                                "remove_private_as": {"type": "bool"},
                                "route_reflector_client": {"type": "bool"},
                                "soft_reconfiguration_inbound": {"type": "bool"},
                                "unsuppress": {"type": "dict", "options": {"policy": {"type": "str"}}},
                            },
                        },
                        "bfd": {"type": "dict", "options": {"enable": {"type": "bool"}, "multihop": {"type": "bool"}}},
                        "connect_retry_interval": {"type": "int"},
                        "ebgp_multihop": {
                            "type": "dict",
                            "options": {"enabled": {"type": "bool"}, "multihopttl": {"type": "int"}},
                        },
                        "graceful_restart": {"type": "dict", "options": {"restart_time": {"type": "int"}}},
                        "hold_time": {"type": "int"},
                        "keepalive_interval": {"type": "int"},
                        "local_as": {"type": "int"},
                        "local_as_options": {
                            "type": "list",
                            "elements": "list",
                            "choices": ["no-prepend", "replace-as"],
                        },
                        "lockout": {"type": "bool"},
                        "minimum_advertisement_interval": {"type": "int"},
                        "passive": {"type": "bool"},
                        "password": {"type": "str", "no_log": True},
                        "peer_group": {"type": "str"},
                        "remote_as": {"type": "int"},
                        "shutdown": {"type": "bool"},
                        "update_source_interface": {"type": "str"},
                    },
                },
                "peer_group": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "description": {"type": "str"},
                        "address_family": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "afi": {"type": "str", "required": True},
                                "safi": {"type": "str", "required": True},
                                "activate": {"type": "bool"},
                                "additional_paths": {
                                    "type": "dict",
                                    "options": {
                                        "type": {
                                            "type": "str",
                                            "choices": ["receive", "send", "send-receive", "disable"],
                                        },
                                        "best_count": {"type": "int"},
                                        "select_all": {"type": "bool"},
                                    },
                                },
                                "advertise_ip_prefix": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "afi": {"type": "str", "choices": ["vpnv4", "vpnv6"], "required": True}
                                    },
                                },
                                "aigp": {
                                    "type": "dict",
                                    "options": {
                                        "enable": {"type": "bool"},
                                        "send": {
                                            "type": "dict",
                                            "options": {
                                                "community": {
                                                    "type": "dict",
                                                    "options": {
                                                        "cost": {"type": "int"},
                                                        "point_of_insertion": {
                                                            "type": "str",
                                                            "choices": ["pre-bestpath", "igp-cost"],
                                                        },
                                                        "transitive": {"type": "bool"},
                                                    },
                                                },
                                                "med": {"type": "bool"},
                                            },
                                        },
                                    },
                                },
                                "allow_as_in": {"type": "int"},
                                "allow_ebgp_sr": {"type": "str", "choices": ["enable", "disable"]},
                                "allow_ebgp_vpn": {"type": "bool"},
                                "attribute_unchanged": {
                                    "type": "list",
                                    "elements": "str",
                                    "choices": ["as-path", "next-hop", "med"],
                                },
                                "default_originate": {"type": "bool"},
                                "default_originate_vpn": {
                                    "type": "dict",
                                    "options": {
                                        "vrf": {
                                            "type": "list",
                                            "elements": "dict",
                                            "options": {"name": {"type": "str", "required": True}},
                                        }
                                    },
                                },
                                "graceful_restart_helper": {"type": "str", "choices": ["disable", "enable"]},
                                "next_hop_self": {"type": "bool"},
                                "orf_mode": {"type": "str", "choices": ["both", "receive", "send"]},
                                "policy": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "direction": {"type": "str", "choices": ["in", "out"], "required": True},
                                        "name": {"type": "str", "required": True},
                                    },
                                },
                                "prefix_limit": {
                                    "type": "dict",
                                    "options": {
                                        "drop_excess": {"type": "float"},
                                        "idle_timeout": {"type": "int"},
                                        "maximum_prefixes": {"type": "int"},
                                        "teardown_threshold": {"type": "float"},
                                        "warning_only": {"type": "bool"},
                                    },
                                },
                                "prefix_list": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "direction": {
                                            "type": "list",
                                            "elements": "str",
                                            "choices": ["in", "out"],
                                            "required": True,
                                        },
                                        "name": {"type": "str", "required": True},
                                    },
                                },
                                "remove_private_as": {"type": "bool"},
                                "route_reflector_client": {"type": "bool"},
                                "soft_reconfiguration_inbound": {"type": "bool"},
                                "unsuppress": {"type": "dict", "options": {"policy": {"type": "str"}}},
                            },
                        },
                        "bfd": {"type": "dict", "options": {"enable": {"type": "bool"}, "multihop": {"type": "bool"}}},
                        "connect_retry_interval": {"type": "int"},
                        "ebgp_multihop": {
                            "type": "dict",
                            "options": {"enabled": {"type": "bool"}, "multihopttl": {"type": "int"}},
                        },
                        "graceful_restart": {"type": "dict", "options": {"restart_time": {"type": "int"}}},
                        "hold_time": {"type": "int"},
                        "keepalive_interval": {"type": "int"},
                        "local_as": {"type": "int"},
                        "local_as_options": {
                            "type": "list",
                            "elements": "list",
                            "choices": ["no-prepend", "replace-as"],
                        },
                        "lockout": {"type": "bool"},
                        "minimum_advertisement_interval": {"type": "int"},
                        "passive": {"type": "bool"},
                        "password": {"type": "str", "no_log": True},
                        "remote_as": {"type": "int"},
                        "shutdown": {"type": "bool"},
                        "update_source_interface": {"type": "str"},
                    },
                },
                "route_selection_options": {
                    "type": "dict",
                    "options": {
                        "aigp_ignore": {"type": "bool"},
                        "always_compare_med": {"type": "bool"},
                        "deterministic_med": {"type": "bool"},
                        "external_compare_router_id": {"type": "bool"},
                        "ignore_as_path_length": {"type": "bool"},
                        "tie_break_on_age": {"type": "bool"},
                    },
                },
                "router_id": {"type": "str"},
                "scan_time": {"type": "int"},
                "segment_routing": {
                    "type": "dict",
                    "options": {
                        "srgb": {
                            "type": "list",
                            "elements": "dict",
                            "options": {"lower_bound": {"type": "int"}, "upper_bound": {"type": "int"}},
                        },
                        "srv6": {"type": "dict", "options": {"locator": {"type": "str"}}},
                    },
                },
                "vrf": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "route_distinguisher": {"type": "str", "required": True},
                        "route_target": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "direction": {"type": "str", "choices": ["import", "export", "both"], "required": True},
                                "id": {"type": "str", "required": True},
                            },
                        },
                        "vrf_address_family": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "afi": {"type": "str", "choices": ["ipv4", "ipv6"], "required": True},
                                "safi": {"type": "str", "choices": ["unicast"], "required": True},
                                "aggregate_address": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "address": {"type": "str", "required": True},
                                        "as_set": {"type": "bool"},
                                        "summary_only": {"type": "bool"},
                                    },
                                },
                                "auto_summary": {"type": "bool"},
                                "network": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "address": {"type": "str", "required": True},
                                        "policy": {"type": "str"},
                                    },
                                },
                                "network_synchronization": {"type": "bool"},
                                "peer": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "address": {"type": "str", "required": True},
                                        "remote_as": {"type": "int", "required": True},
                                        "description": {"type": "str"},
                                        "activate": {"type": "bool"},
                                        "aigp": {
                                            "type": "dict",
                                            "options": {
                                                "enable": {"type": "bool"},
                                                "send": {
                                                    "type": "dict",
                                                    "options": {
                                                        "community": {
                                                            "type": "dict",
                                                            "options": {
                                                                "cost": {"type": "int"},
                                                                "point_of_insertion": {
                                                                    "type": "str",
                                                                    "choices": ["pre-bestpath", "igp-cost"],
                                                                },
                                                                "transitive": {"type": "bool"},
                                                            },
                                                        },
                                                        "med": {"type": "bool"},
                                                    },
                                                },
                                            },
                                        },
                                        "allow_as_in": {"type": "int"},
                                        "allow_ebgp_vpn": {"type": "bool"},
                                        "as_override": {"type": "bool"},
                                        "attribute_unchanged": {
                                            "type": "list",
                                            "elements": "str",
                                            "choices": ["as-path", "next-hop", "med"],
                                        },
                                        "bfd": {
                                            "type": "dict",
                                            "options": {"enable": {"type": "bool"}, "multihop": {"type": "bool"}},
                                        },
                                        "connect_retry_interval": {"type": "int"},
                                        "ebgp_multihop": {
                                            "type": "dict",
                                            "options": {"enabled": {"type": "bool"}, "multihop_ttl": {"type": "int"}},
                                        },
                                        "graceful_restart": {
                                            "type": "dict",
                                            "options": {"restart_time": {"type": "int"}},
                                        },
                                        "graceful_restart_helper": {"type": "str", "choices": ["disable", "enable"]},
                                        "hold_time": {"type": "int"},
                                        "keepalive_interval": {"type": "int"},
                                        "local_as": {"type": "int"},
                                        "local_as_options": {
                                            "type": "list",
                                            "elements": "list",
                                            "choices": ["no-prepend", "replace-as"],
                                        },
                                        "lockout": {"type": "bool"},
                                        "minimum_advertisement_interval": {"type": "int"},
                                        "orf_mode": {"type": "str", "choices": ["both", "receive", "send"]},
                                        "passive": {"type": "bool"},
                                        "password": {"type": "str", "no_log": True},
                                        "policy": {
                                            "type": "list",
                                            "elements": "dict",
                                            "options": {
                                                "direction": {
                                                    "type": "str",
                                                    "choices": ["in", "out"],
                                                    "required": True,
                                                },
                                                "name": {"type": "str", "required": True},
                                            },
                                        },
                                        "prefix_limit": {
                                            "type": "dict",
                                            "options": {
                                                "drop_excess": {"type": "float"},
                                                "idle_timeout": {"type": "int"},
                                                "maximum_prefixes": {"type": "int"},
                                                "teardown_threshold": {"type": "float"},
                                                "warning_only": {"type": "bool"},
                                            },
                                        },
                                        "prefix_list": {
                                            "type": "list",
                                            "elements": "dict",
                                            "options": {
                                                "direction": {
                                                    "type": "list",
                                                    "elements": "str",
                                                    "choices": ["in", "out"],
                                                    "required": True,
                                                },
                                                "name": {"type": "str", "required": True},
                                            },
                                        },
                                        "remove_private_as": {"type": "bool"},
                                        "route_reflector_client": {"type": "bool"},
                                        "shutdown": {"type": "bool"},
                                        "site_origin_id": {"type": "str"},
                                        "soft_reconfiguration_inbound": {"type": "bool"},
                                        "unsuppress": {"type": "dict", "options": {"policy": {"type": "str"}}},
                                        "update_source_interface": {"type": "str"},
                                    },
                                },
                                "redistribute": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "protocol": {
                                            "type": "str",
                                            "choices": ["kernel", "connected", "static", "rip", "isis", "ospf"],
                                            "required": True,
                                        },
                                        "instance": {
                                            "type": "list",
                                            "elements": "dict",
                                            "options": {
                                                "tag": {"type": "str", "required": True},
                                                "policy": {"type": "str"},
                                            },
                                        },
                                        "policy": {"type": "str"},
                                    },
                                },
                                "route_target": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "direction": {
                                            "type": "str",
                                            "choices": ["import", "export", "both"],
                                            "required": True,
                                        },
                                        "id": {"type": "str", "required": True},
                                    },
                                },
                                "segment_routing_srv6": {"type": "dict", "options": {"locator": {"type": "str"}}},
                                "synchronization": {"type": "bool"},
                            },
                        },
                    },
                },
            },
        },
        "state": {"type": "str", "default": "merged", "choices": ["merged", "deleted"]},
    }  # pylint: disable=C0301
