#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2025 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for saos10_isis
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type


DOCUMENTATION = """
---
module: saos10_isis
short_description: Manage isis instance on Ciena saos10 devices.
description: List of IS-IS structures.. IS-IS structure
author: Ciena
options:
  config:
    description: IS-IS structure
    type: list
    elements: dict
    suboptions:
      admin_state:
        description: Enable/Disable the protocol.
        type: bool
        required: false
      cspf_flag:
        description: Enable cspf flag
        type: bool
        required: false
      distance:
        description: The administrative distance assigned to routes discovered by the IS-IS protocol,
        type: int
        required: false
      distribute:
        description: Distribute information to another routing protocol
        type: dict
        suboptions:
          bgp_ls_id:
            description: BGP-LS ID configuration
            type: int
            required: false
          protocol:
            description: Protocol name to which information to be dstributed
            type: str
            required: false
            choices:
            - bgp-ls
          throttle:
            description: Throttle timer for distributing information to another routing protocol
            type: int
            required: false
      dynamic_hostname:
        description: If TRUE, dynamic hostname resolution is enabled, and system IDs will always be displayed by show and debug output.
        type: bool
        required: false
      fast_reroute:
        description: Configurations for ISIS LFA fast reroute
        type: dict
        suboptions:
          hold_timer:
            description: Hold timer in msec when packet forwarding through LFA is in effect
            type: int
            required: false
          level:
            description: Enable/disable LFA for ISIS level-1 or level-2
            type: list
            elements: dict
            suboptions:
              level_type:
                description: 'Level of an IS-IS node, either level-1 or level-2 (Key for list: level)'
                type: str
                required: true
                choices:
                - level-1
                - level-2
              lfa:
                description: IS-IS LFA fast-reroute
                type: dict
                suboptions:
                  per_prefix_enable:
                    description: Enables/disables LFA FRR
                    type: bool
                    required: false
                  preference:
                    description: Preference for each of the LFA options
                    type: list
                    elements: dict
                    suboptions:
                      address_family:
                        description: 'IPv4 or IPv6 address family (Key for list: preference)'
                        type: str
                        required: true
                        choices:
                        - ipv4
                      priority:
                        description: Sets the priority value for each tie-breaker, lower value higher priority
                        type: list
                        elements: dict
                        suboptions:
                          tie_breaker:
                            description: 'Tie-breakers used to select the best alternate route (Key for list: priority)'
                            type: str
                            required: true
                            choices:
                            - primary-path
                            - node-protecting
                            - secondary-path
                            - downstream-path
                          value:
                            description: Priority value associated with the tie-breaker
                            type: int
                            required: false
                        key: tie-breaker
                    key: address-family
                  remote_lfa:
                    description: Configurations for remote ISIS LFA fast reroute
                    type: dict
                    suboptions:
                      per_prefix_enable:
                        description: Enables/disables remote LFA FRR
                        type: bool
                        required: false
                      protection:
                        description: Protection provided to the repair tunnel
                        type: list
                        elements: dict
                        suboptions:
                          enable:
                            description: Enable/disable the protection type
                            type: bool
                            required: false
                          protection_type:
                            description: 'The protection type (Key for list: protection)'
                            type: str
                            required: true
                            choices:
                            - downstream-protection
                        key: protection-type
                      tunnel_cost:
                        description: Maximum cost of the repair tunnel.
                        type: int
                        required: false
                  ti_lfa:
                    description: Configurations for ISIS TI-LFA fast reroute
                    type: dict
                    suboptions:
                      per_prefix_enable:
                        description: Enables/disables topology independent FRR
                        type: bool
                        required: false
            key: level-type
      graceful_restart:
        description: NOT SUPPORTED under IS-IS instance, moved to global routing command. Obsolete next release.
        type: dict
        suboptions:
          helper_enable:
            description: NOT SUPPORTED under IS-IS instance, moved to global routing command. Obsolete next release.
            type: bool
            required: false
          max_recovery_time:
            description: Graceful restart T3 timer (max time for recovery)
            type: int
            required: false
          max_restart_time:
            description: Graceful restart T1 timer
            type: int
            required: false
          restart_capable:
            description: NOT SUPPORTED under IS-IS instance, moved to global routing command. Obsolete next release.
            type: bool
            required: false
      interfaces:
        description: Configure IS-IS interface
        type: dict
        suboptions:
          interface:
            description: ISIS interface related operations
            type: list
            elements: dict
            suboptions:
              address_families:
                description: Address families that takes Afi and Safi related configuration in interface mode
                type: dict
                suboptions:
                  address_family:
                    description: List IS-IS Address Family that takes Afi and Safi related configuration
                    type: list
                    elements: dict
                    suboptions:
                      afi:
                        description: 'Enter the IPv4, or IPv6 address family mode allowing configuration of Address-family specific parameters
                          (Key for list: address-family)'
                        type: str
                        required: true
                        choices:
                        - ipv4
                        - ipv6
                      safi:
                        description: 'Configure sub address family such as unicast (Key for list: address-family)'
                        type: str
                        required: true
                        choices:
                        - unicast
                    key: afi safi
              admin_state:
                description: Enable/Disable the protocol.
                type: bool
                required: false
              bfd:
                description: Configure bidirectional forwarding detection for address family IPv4 for ISIS.
                type: dict
                suboptions:
                  enable:
                    description: Enable BFD.
                    type: bool
                    required: false
              bfd_ipv6:
                description: Configure bidirectional forwarding detection for address family IPv6 for ISIS.
                type: dict
                suboptions:
                  enable_ipv6:
                    description: Enable BFD IPv6.
                    type: bool
                    required: false
              hello_padding:
                description: IS-IS Hello-padding activation - enabled by default.
                type: bool
                required: false
              interface_type:
                description: Type of adjacency to be established on the interface. This dictates the type of hello messages that are used.
                type: str
                required: false
                choices:
                - broadcast
                - point-to-point
              ipv4_unicast_default_disable:
                description: Set this flag (to true) to disable default config for IPv4 AF on interface.
                type: bool
                required: false
              ldp_igp_sync:
                description: Enables IGP/LDP synchronization
                type: list
                elements: dict
                suboptions:
                  hold_down:
                    description: Hold-down timer for the ISIS ldp-igp synchronization configuration
                    type: str
                    required: true
                  level_type:
                    description: 'Enable MPLS LDP Synchronization for an IS-IS level - can be level-1, level-2 or level-1-2. (Key for list: ldp-igp-sync)'
                    type: str
                    required: true
                    choices:
                    - level-1
                    - level-2
                    - level-1-2
                key: level-type
              level_1:
                description: Interface level-1 specific configuration
                type: dict
                suboptions:
                  auth_type:
                    description: Interface authentication type (MD5/text)
                    type: str
                    required: false
                    choices:
                    - md5
                    - text
                  csnp_interval:
                    description: Interval between CSNP messages.
                    type: int
                    required: false
                  gr_restart_hello_interval:
                    description: IS-IS Graceful restart T1 timer interval
                    type: int
                    required: false
                  hello_interval:
                    description: Interval between hello messages
                    type: int
                    required: false
                  hello_multiplier:
                    description: Number of missed hello messages prior to adjacency down grouping.
                    type: int
                    required: false
                  lfa_candidate_enable:
                    description: Enable/disable the interface from being used as LFA for a level-1 primary route
                    type: bool
                    required: false
                  metric:
                    description: Narrow metric IS-IS interface configuration.
                    type: int
                    required: false
                  password:
                    description: Password string for interface authentication using HMAC-MD5
                    type: str
                    required: false
                  priority:
                    description: Priority for DIS election.
                    type: int
                    required: false
                  send_only:
                    description: Only send encrypted packets, ignore auth on received PDUs
                    type: bool
                    required: false
                  tag:
                    description: Level-1 tag for LSPs sent out advertising routes for networks directly connected to an interface.
                    type: int
                    required: false
                  wide_metric:
                    description: Wide-metric configuration
                    type: int
                    required: false
              level_2:
                description: Interface level-2 specific configuration
                type: dict
                suboptions:
                  auth_type:
                    description: Interface authentication type (MD5/text)
                    type: str
                    required: false
                    choices:
                    - md5
                    - text
                  csnp_interval:
                    description: Interval between CSNP messages.
                    type: int
                    required: false
                  gr_restart_hello_interval:
                    description: IS-IS Graceful restart T1 timer interval
                    type: int
                    required: false
                  hello_interval:
                    description: Interval between hello messages
                    type: int
                    required: false
                  hello_multiplier:
                    description: Number of missed hello messages prior to adjacency down grouping.
                    type: int
                    required: false
                  lfa_candidate_enable:
                    description: Enable/disable the interface from being used as LFA for a level-2 primary route
                    type: bool
                    required: false
                  metric:
                    description: Narrow metric configuration.
                    type: int
                    required: false
                  password:
                    description: Password string for interface authentication using HMAC-MD5
                    type: str
                    required: false
                  priority:
                    description: Priority for DIS election.
                    type: int
                    required: false
                  send_only:
                    description: Only send encrypted packets, ignore auth on received PDUs
                    type: bool
                    required: false
                  tag:
                    description: Level-2 tag for LSPs sent out advertising routes for networks directly connected to an interface.
                    type: int
                    required: false
                  wide_metric:
                    description: Wide-metric configuration
                    type: int
                    required: false
              level_type:
                description: Level of an IS-IS node - can be level-1, level-2 or level-1-2.
                type: str
                required: false
                choices:
                - level-1
                - level-2
                - level-1-2
              lsp_interval:
                description: Interval between LSP transmissions.
                type: int
                required: false
              lsp_retransmit_interval:
                description: Interval between LSP retransmissions.
                type: int
                required: false
              name:
                description: 'L3 Interface name (Key for list: interface)'
                type: str
                required: true
            key: name
      ispf_levels:
        description: The i-spf level of an IS-IS node - can be level-1, level-2 or level-1-2.
        type: str
        required: false
        choices:
        - level-1
        - level-2
        - level-1-2
      level_1:
        description: Level-1 specific configuration
        type: dict
        suboptions:
          area_auth:
            description: Area authentication specific configuration
            type: dict
            suboptions:
              auth_type:
                description: Interface authentication type (MD5/text)
                type: str
                required: false
                choices:
                - md5
                - text
              password:
                description: MD5/text authentication password
                type: str
                required: false
              send_only:
                description: Only send encrypted packets, ignore auth on received PDUs
                type: bool
                required: false
              snp_auth:
                description: Authenticate SNP PDUs
                type: bool
                required: false
          lsp_gen_interval:
            description: Set minimum interval before regenerating the same LSP. The smaller the interval, the faster the convergence.
            type: int
            required: false
          lsp_mtu:
            description: Maximum size of an LSP PDU
            type: int
            required: false
          recovery_time:
            description: Graceful restart T2 timer (level DB sync recovery time)
            type: int
            required: false
          spf_max_delay:
            description: Maximum delay between receiving a change to SPF calculation
            type: int
            required: false
          spf_min_delay:
            description: Minimum delay between receiving a change to SPF calculation
            type: int
            required: false
      level_2:
        description: Level-2 specific configuration
        type: dict
        suboptions:
          domain_auth:
            description: Domain authentication specific configuration
            type: dict
            suboptions:
              auth_type:
                description: Interface authentication type (MD5/text)
                type: str
                required: false
                choices:
                - md5
                - text
              password:
                description: MD5/text authentication password
                type: str
                required: false
              send_only:
                description: Only send encrypted packets, ignore auth on received PDUs
                type: bool
                required: false
              snp_auth:
                description: Authenticate SNP PDUs
                type: bool
                required: false
          lsp_gen_interval:
            description: Set minimum interval before regenerating the same LSP. The smaller the interval, the faster the convergence.
            type: int
            required: false
          lsp_mtu:
            description: Maximum size of an LSP PDU
            type: int
            required: false
          recovery_time:
            description: Graceful restart T2 timer (level DB sync recovery time)
            type: int
            required: false
          spf_max_delay:
            description: Maximum delay between receiving a change to SPF calculation
            type: int
            required: false
          spf_min_delay:
            description: Minimum delay between receiving a change to SPF calculation
            type: int
            required: false
      level_type:
        description: Level of an IS-IS node - can be level-1, level-2 or level-1-2.
        type: str
        required: false
        choices:
        - level-1
        - level-2
        - level-1-2
      lsp_lifetime:
        description: Lifetime of the router's LSPs in seconds.
        type: int
        required: false
      lsp_refresh:
        description: Refresh interval of the router's LSPs
        type: int
        required: false
      metric_style:
        description: Metric style global configuration
        type: str
        required: false
        choices:
        - wide
      microloop_avoidance:
        description: ISIS microloop-avoidance configuration.
        type: dict
        suboptions:
          enable:
            description: Enable/disable microloop avoidance for protected prefixes.
            type: bool
            required: false
          rib_update_delay:
            description: Set route download delay for microloop avoidance on local interfaces.
            type: int
            required: false
      mpls_te:
        description: Routing protocol commands for MPLS Traffic Engineering
        type: dict
        suboptions:
          level_type:
            description: Level of ISIS-TE node
            type: str
            required: false
          router_id:
            description: Router ID to be set
            type: str
            required: false
      multi_topology:
        description: Support for Multiple-Topology Routing (MTR), RFC5120 - M-IS-IS; Multi Topology Routing in IS-IS
        type: list
        elements: dict
        suboptions:
          level:
            description: 'Level of an IS-IS multitoplogy support (Key for list: multi-topology)'
            type: str
            required: true
            choices:
            - level-1
            - level-2
            - level-1-2
          transition:
            description: Specify to accept and generate both IS-IS IPv6 and multi-topology IPv6 TLVs
            type: bool
            required: false
        key: level
      net:
        description: System-id of the node.
        type: list
        elements: str
      overload:
        description: Router protocol instance overload state configuration
        type: dict
        suboptions:
          on_startup:
            description: Overload interval after reboot
            type: str
            required: false
            choices:
            - wait-for-bgp
            - time-out
          suppress:
            description: Overload bit flags
            type: str
            required: false
            choices:
            - external
            - interlevel
            - external-interlevel
            - interlevel-external
          timeout:
            description: Applicable only when on-startup is set to time-out.
            type: int
            required: false
      passive:
        description: Indicates whetherthe interface is in passive mode (IS-IS not running but network is advertised).
        type: list
        elements: dict
        suboptions:
          passive_if_name:
            description: 'Interface name (Key for list: passive)'
            type: str
            required: true
        key: passive-if-name
      proto_ipv4:
        description: IS-IS protocol IPv4 redistribute configuration
        type: dict
        suboptions:
          redistribute:
            description: IS-IS protocol IPv4 redistribute configuration
            type: dict
            suboptions:
              level:
                description: IS-IS protocol redistribute configuration
                type: list
                elements: dict
                suboptions:
                  type:
                    description: 'Redistributes from level 1to2 or level 2to1 (Key for list: level)'
                    type: str
                    required: true
                    choices:
                    - 1to2
                    - 2to1
                  prefix_list:
                    description: Refers to a prefix list name
                    type: str
                    required: false
                key: type
              origin:
                description: Origin type; originate or originate-always
                type: str
                required: false
                choices:
                - originate
                - originate-always
              policy:
                description: Refers to an existing policy name
                type: str
                required: false
              protocol:
                description: Redistribute routes from static, bgp, ospf, connected into IS-IS levels
                type: list
                elements: dict
                suboptions:
                  level:
                    description: IS-IS level
                    type: str
                    required: false
                    choices:
                    - level-1
                    - level-2
                    - level-1-2
                  metric:
                    description: IS-IS metric
                    type: int
                    required: false
                  name:
                    description: 'Source protocol name to redistribute from (bgp, ospf, static, connected) (Key for list: protocol)'
                    type: str
                    required: true
                    choices:
                    - connected
                    - static
                    - ospf
                    - bgp
                  policy:
                    description: Refers to an existing policy name
                    type: str
                    required: false
                key: name
          summary_address:
            description: List of summary address used for route summarization
            type: list
            elements: dict
            suboptions:
              address:
                description: 'IP network prefix (Key for list: summary-address)'
                type: str
                required: true
              level:
                description: Summarize into level-1 area or both area and sub-domain or level-2 sub-domain
                type: str
                required: false
                choices:
                - level-1
                - level-2
                - level-1-2
              metric:
                description: Metric used for the summarized address
                type: int
                required: true
            key: address
      proto_ipv6:
        description: IS-IS protocol IPv6 redistribute configuration
        type: dict
        suboptions:
          redistribute:
            description: IS-IS protocol IPv6 redistribute configuration
            type: dict
            suboptions:
              adjacency_check:
                description: Suppress checking of consistent AF support on received IIHs
                type: bool
                required: false
              distance:
                description: The administrative distance assigned to routes discovered by the IS-IS protocol,
                type: int
                required: false
              level:
                description: IS-IS protocol redistribute configuration
                type: list
                elements: dict
                suboptions:
                  type:
                    description: 'Redistributes from level 1to2 or level 2to1 (Key for list: level)'
                    type: str
                    required: true
                    choices:
                    - 1to2
                    - 2to1
                  prefix_list:
                    description: Refers to a prefix list name
                    type: str
                    required: false
                key: type
              origin:
                description: Origin type; originate
                type: str
                required: false
                choices:
                - originate
              policy:
                description: Refers to an existing policy name
                type: str
                required: false
              protocol:
                description: Redistribute routes from static, bgp, ospf, connected into IS-IS levels
                type: list
                elements: dict
                suboptions:
                  level:
                    description: IS-IS level
                    type: str
                    required: false
                    choices:
                    - level-1
                    - level-2
                    - level-1-2
                  metric:
                    description: IS-IS metric
                    type: int
                    required: false
                  name:
                    description: 'Source protocol name to redistribute from (bgp, ospf, static, connected) (Key for list: protocol)'
                    type: str
                    required: true
                    choices:
                    - connected
                    - static
                    - ospf
                    - bgp
                  policy:
                    description: Refers to an existing policy name
                    type: str
                    required: false
                key: name
          summary_address:
            description: List of summary address used for route summarization
            type: list
            elements: dict
            suboptions:
              address:
                description: 'IP network prefix (Key for list: summary-address)'
                type: str
                required: true
              level:
                description: Summarize into level-1 area or both area and sub-domain or level-2 sub-domain
                type: str
                required: false
                choices:
                - level-1
                - level-2
                - level-1-2
              metric:
                description: Metric used for the summarized address
                type: int
                required: true
            key: address
      segment_routing:
        description: Attribute to enable MPLS-based segment routing for an ISIS or OSPF process.
        type: dict
        suboptions:
          bindings:
            description: Attribute to enable prefix sid map local/receive
            type: dict
            suboptions:
              advertise:
                description: Enables/disables prefix sid map type local
                type: bool
                required: false
              receive:
                description: Enables/disables prefix sid map type receive
                type: bool
                required: false
          enabled:
            description: Enable MPLS Segment Routing
            type: bool
            required: false
          force_php:
            description: Attribute to configure Force PHP
            type: dict
            suboptions:
              enable:
                description: Enable/disable Force PHP
                type: bool
                required: false
          srgb:
            description: List of global blocks to be advertised.
            type: list
            elements: dict
            suboptions:
              lower_bound:
                description: 'Lower value in the block. (Key for list: srgb)'
                type: int
                required: true
              upper_bound:
                description: 'Upper value in the block. (Key for list: srgb)'
                type: int
                required: true
            key: lower-bound upper-bound
      tag:
        description: 'IS-IS instance area tag (Key for list: instance)'
        type: str
        required: true
    key: tag
  state:
    description: The state of the configuration after module completion.
    type: str
    choices:
    - merged
    - deleted
    default: merged

"""
EXAMPLES = """
# Using merged

- name: Configure TODO
  ciena.saos10.saos10_TODO:
    config:
      - name: untagged
        filter_entry:
          - filter_parameter: vtag-stack
            untagged_exclude_priority_tagged: false
      - name: foo-100
        filter_entry:
          - filter_parameter: vtag-stack
            vtags:
              - tag: 1
                vlan_id: 100
    state: merged
# Using deleted

- name: Delete TODO
  ciena.saos10.saos10_TODO:
    config:
      - name: TODO
    state: deleted
"""

RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  type: dict
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  type: dict
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
xml:
  description: The set of xml commands pushed to the remote device.
  returned: always
  type: list
  sample: ['<system xmlns="http://openconfig.net/yang/system"><config><hostname>foo</hostname></config></system>']
"""

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.ciena.saos10.plugins.module_utils.network.saos10.argspec.isis.isis import (
    IsisArgs,
)
from ansible_collections.ciena.saos10.plugins.module_utils.network.saos10.config.isis.isis import (
    Isis,
)


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=IsisArgs.argument_spec, supports_check_mode=True)

    result = Isis(module).execute_module()
    module.exit_json(**result)


if __name__ == "__main__":
    main()
